# -*- coding: utf-8 -*-
"""repeticao

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13tESCt95f7dIpx7uhw4YYVS7IIxmCnYa
"""

notas = []

for x in range (4):
    codigo_aluno = (input ("RM: "))
    nota = float(input("nota: "))
    resultado = [codigo_aluno, nota]
    notas.append(resultado)

print("quantidade de notas", len(notas))

for n in notas:
    codigo_aluno = n[0]
    nota = n[1]
    print("o rm", codigo_aluno, "tirou a nota:", nota)